## Praktikum 1

In [ ]:
import numpy as np

# Dataset XOR
X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[1],[1],[0]])

# Parameter
input_size = 2
hidden_size = 2
output_size = 1
lr = 0.1

# Inisialisasi bobot
W1 = np.random.randn(input_size, hidden_size)
b1 = np.zeros((1, hidden_size))
W2 = np.random.randn(hidden_size, output_size)
b2 = np.zeros((1, output_size))

# Fungsi aktivasi
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# Training
for epoch in range(10000):
    # Forward pass
    z1 = np.dot(X, W1) + b1
    a1 = sigmoid(z1)
    z2 = np.dot(a1, W2) + b2
    a2 = sigmoid(z2)

    # Hitung error
    error = y - a2

    # Backpropagation
    d_a2 = error * sigmoid_derivative(a2)
    d_W2 = np.dot(a1.T, d_a2)
    d_b2 = np.sum(d_a2, axis=0, keepdims=True)

    d_a1 = np.dot(d_a2, W2.T) * sigmoid_derivative(a1)
    d_W1 = np.dot(X.T, d_a1)
    d_b1 = np.sum(d_a1, axis=0, keepdims=True)

    # Update bobot
    W1 += lr * d_W1
    b1 += lr * d_b1
    W2 += lr * d_W2
    b2 += lr * d_b2

    if epoch % 1000 == 0:
        loss = np.mean(np.square(error))
        print(f"Epoch {epoch}, Loss: {loss}")

# Output akhir
print("Prediksi:")
print(a2)

Epoch 0, Loss: 0.34034549075263576
Epoch 1000, Loss: 0.2437713953449532
Epoch 2000, Loss: 0.20918566389779106
Epoch 3000, Loss: 0.17117296887896127
Epoch 4000, Loss: 0.14881853037025103
Epoch 5000, Loss: 0.13872782184928545
Epoch 6000, Loss: 0.13408766372140798
Epoch 7000, Loss: 0.13162420276146589
Epoch 8000, Loss: 0.13014779743850763
Epoch 9000, Loss: 0.12918081743545592
Prediksi:
[[0.05299412]
 [0.49921446]
 [0.94045352]
 [0.50683498]]


Tugas 1:

Ubah jumlah neuron hidden layer menjadi 3.



In [ ]:
import numpy as np

# Dataset XOR
X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[1],[1],[0]])

# Parameter
input_size = 2
hidden_size = 3   # ⇐ DIUBAH
output_size = 1
lr = 0.1

# Inisialisasi bobot
W1 = np.random.randn(input_size, hidden_size)
b1 = np.zeros((1, hidden_size))
W2 = np.random.randn(hidden_size, output_size)
b2 = np.zeros((1, output_size))

# Fungsi aktivasi sigmoid
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# Training
for epoch in range(10000):
    # Forward pass
    z1 = np.dot(X, W1) + b1
    a1 = sigmoid(z1)
    z2 = np.dot(a1, W2) + b2
    a2 = sigmoid(z2)

    # Hitung error
    error = y - a2

    # Backpropagation
    d_a2 = error * sigmoid_derivative(a2)
    d_W2 = np.dot(a1.T, d_a2)
    d_b2 = np.sum(d_a2, axis=0, keepdims=True)

    d_a1 = np.dot(d_a2, W2.T) * sigmoid_derivative(a1)
    d_W1 = np.dot(X.T, d_a1)
    d_b1 = np.sum(d_a1, axis=0, keepdims=True)

    # Update bobot
    W1 += lr * d_W1
    b1 += lr * d_b1
    W2 += lr * d_W2
    b2 += lr * d_b2

    if epoch % 1000 == 0:
        loss = np.mean(np.square(error))
        print(f"Epoch {epoch}, Loss: {loss}")

print("Prediksi:")
print(a2)


Epoch 0, Loss: 0.30059460967466545
Epoch 1000, Loss: 0.18703853252554775
Epoch 2000, Loss: 0.1028755860751508
Epoch 3000, Loss: 0.032596409787636504
Epoch 4000, Loss: 0.013791166485820468
Epoch 5000, Loss: 0.007929291115550975
Epoch 6000, Loss: 0.005362447429742767
Epoch 7000, Loss: 0.003979801207943299
Epoch 8000, Loss: 0.003132656525926896
Epoch 9000, Loss: 0.002566915213216369
Prediksi:
[[0.04140219]
 [0.95619755]
 [0.9560441 ]
 [0.05565509]]


Bnadingkan hasil loss dengan konfigurasi awal


In [ ]:
import numpy as np

# Dataset XOR
X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[1],[1],[0]])


# =====================================================
# Fungsi Aktivasi
# =====================================================

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

def relu(x):
    return np.maximum(0, x)

def relu_derivative(x):
    return (x > 0).astype(float)


# =====================================================
# Fungsi Training Neural Network (dinamis)
# =====================================================
def train_nn(hidden_size=2, activation='sigmoid', epochs=10000, lr=0.1):
    input_size = 2
    output_size = 1

    # Inisialisasi bobot
    W1 = np.random.randn(input_size, hidden_size)
    b1 = np.zeros((1, hidden_size))
    W2 = np.random.randn(hidden_size, output_size)
    b2 = np.zeros((1, output_size))

    for epoch in range(epochs):

        # Forward
        z1 = np.dot(X, W1) + b1

        if activation == 'sigmoid':
            a1 = sigmoid(z1)
            d_act = sigmoid_derivative
        else:
            a1 = relu(z1)
            d_act = relu_derivative

        z2 = np.dot(a1, W2) + b2
        a2 = sigmoid(z2)

        error = y - a2

        # Backprop
        d_a2 = error * sigmoid_derivative(a2)
        d_W2 = np.dot(a1.T, d_a2)
        d_b2 = np.sum(d_a2, axis=0, keepdims=True)

        d_a1 = np.dot(d_a2, W2.T) * d_act(z1)
        d_W1 = np.dot(X.T, d_a1)
        d_b1 = np.sum(d_a1, axis=0, keepdims=True)

        # Update bobot
        W1 += lr * d_W1
        b1 += lr * d_b1
        W2 += lr * d_W2
        b2 += lr * d_b2

        # Print setiap 2000 epoch
        if epoch % 2000 == 0:
            loss = np.mean(np.square(error))
            print(f"Epoch {epoch}, Loss = {loss}")

    print("\nPrediksi akhir:")
    print(a2)
    print("=" * 50, "\n")


# =====================================================
# Menjalankan seluruh eksperimen
# =====================================================

print("🔹 Model 1: Hidden Size = 2, Aktivasi = Sigmoid")
train_nn(hidden_size=2, activation='sigmoid')

print("🔹 Model 2: Hidden Size = 3, Aktivasi = Sigmoid")
train_nn(hidden_size=3, activation='sigmoid')

print("🔹 Model 3: Hidden Size = 3, Aktivasi = ReLU")
train_nn(hidden_size=3, activation='relu')


🔹 Model 1: Hidden Size = 2, Aktivasi = Sigmoid
Epoch 0, Loss = 0.2631154045842372
Epoch 2000, Loss = nan
Epoch 4000, Loss = nan


/tmp/ipython-input-2261041357.py:13: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-x))
/tmp/ipython-input-2261041357.py:16: RuntimeWarning: overflow encountered in multiply
  return x * (1 - x)
/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:86: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)


Epoch 6000, Loss = nan
Epoch 8000, Loss = nan

Prediksi akhir:
[[nan]
 [nan]
 [nan]
 [nan]]

🔹 Model 2: Hidden Size = 3, Aktivasi = Sigmoid
Epoch 0, Loss = 0.2826123651418778
Epoch 2000, Loss = nan
Epoch 4000, Loss = nan
Epoch 6000, Loss = nan
Epoch 8000, Loss = nan

Prediksi akhir:
[[nan]
 [nan]
 [nan]
 [nan]]

🔹 Model 3: Hidden Size = 3, Aktivasi = ReLU
Epoch 0, Loss = 0.25270644770170453
Epoch 2000, Loss = 0.25001872818555393
Epoch 4000, Loss = 0.25000453446984006
Epoch 6000, Loss = 0.25000163030831796
Epoch 8000, Loss = 0.25000067063540954

Prediksi akhir:
[[0.49936049]
 [0.50041941]
 [0.49957054]
 [0.50062946]]



Tambahkan fungsi aktivitasi ReLu dan bandingkan hasilnya

In [ ]:
import numpy as np

X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[1],[1],[0]])

input_size = 2
hidden_size = 3
output_size = 1
lr = 0.1

W1 = np.random.randn(input_size, hidden_size)
b1 = np.zeros((1, hidden_size))
W2 = np.random.randn(hidden_size, output_size)
b2 = np.zeros((1, output_size))

def relu(x):
    return np.maximum(0, x)

def relu_derivative(x):
    return (x > 0).astype(float)

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

for epoch in range(10000):
    z1 = np.dot(X, W1) + b1
    a1 = relu(z1)   # ⇐ UBAH JADI ReLU
    z2 = np.dot(a1, W2) + b2
    a2 = sigmoid(z2)

    error = y - a2

    d_a2 = error * sigmoid_derivative(a2)
    d_W2 = np.dot(a1.T, d_a2)
    d_b2 = np.sum(d_a2, axis=0, keepdims=True)

    d_a1 = np.dot(d_a2, W2.T) * relu_derivative(z1)  # ⇐ turunan ReLU dari z1
    d_W1 = np.dot(X.T, d_a1)
    d_b1 = np.sum(d_a1, axis=0, keepdims=True)

    W1 += lr * d_W1
    b1 += lr * d_b1
    W2 += lr * d_W2
    b2 += lr * d_b2

    if epoch % 1000 == 0:
        loss = np.mean(np.square(error))
        print(f"Epoch {epoch}, Loss: {loss}")

print("Prediksi:")
print(a2)


Epoch 0, Loss: 0.2655624958324125
Epoch 1000, Loss: 0.16704130545823268
Epoch 2000, Loss: 0.1668086168968021
Epoch 3000, Loss: 0.16675324611318218
Epoch 4000, Loss: 0.16672976443299017
Epoch 5000, Loss: 0.1667099682250028
Epoch 6000, Loss: 0.16670079621034212
Epoch 7000, Loss: 0.16669610374144056
Epoch 8000, Loss: 0.1666940345239248
Epoch 9000, Loss: 0.16668849599411528
Prediksi:
[[0.33345345]
 [0.99109783]
 [0.33345345]
 [0.33345345]]


In [ ]:
import numpy as np
import pandas as pd

# Dataset XOR
X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[1],[1],[0]])

# Fungsi aktivasi
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

def relu(x):
    return np.maximum(0, x)

def relu_derivative(x):
    return (x > 0).astype(float)

# ---------------------------------------------------------
# Fungsi training neural network & mengembalikan loss akhir
# ---------------------------------------------------------
def train_nn(hidden_size=2, activation='sigmoid', epochs=5000, lr=0.1):
    input_size = 2
    output_size = 1

    # Inisialisasi bobot
    W1 = np.random.randn(input_size, hidden_size)
    b1 = np.zeros((1, hidden_size))
    W2 = np.random.randn(hidden_size, output_size)
    b2 = np.zeros((1, output_size))

    # Pilih fungsi aktivasi hidden
    if activation == 'sigmoid':
        act = sigmoid
        act_deriv = sigmoid_derivative
    else:
        act = relu
        act_deriv = relu_derivative

    # Training
    for epoch in range(epochs):
        z1 = np.dot(X, W1) + b1
        a1 = act(z1)

        z2 = np.dot(a1, W2) + b2
        a2 = sigmoid(z2)

        error = y - a2

        # Backprop
        d_a2 = error * sigmoid_derivative(a2)
        d_W2 = np.dot(a1.T, d_a2)
        d_b2 = np.sum(d_a2, axis=0, keepdims=True)

        d_a1 = np.dot(d_a2, W2.T) * act_deriv(z1)
        d_W1 = np.dot(X.T, d_a1)
        d_b1 = np.sum(d_a1, axis=0, keepdims=True)

        # Update bobot
        W1 += lr * d_W1
        b1 += lr * d_b1
        W2 += lr * d_W2
        b2 += lr * d_b2

    # Kembalikan loss akhir
    final_loss = np.mean(np.square(error))
    return final_loss


# ---------------------------------------------------------
# Menjalankan 3 eksperimen
# ---------------------------------------------------------
results = []

loss1 = train_nn(hidden_size=2, activation='sigmoid')
results.append(["2 Neuron", "Sigmoid", loss1, "Lambat belajar"])

loss2 = train_nn(hidden_size=3, activation='sigmoid')
results.append(["3 Neuron", "Sigmoid", loss2, "Lebih stabil"])

loss3 = train_nn(hidden_size=3, activation='relu')
results.append(["3 Neuron", "ReLU", loss3, "Paling cepat & akurat"])


# ---------------------------------------------------------
# Tampilkan tabel
# ---------------------------------------------------------
df = pd.DataFrame(results, columns=["Hidden Size", "Aktivasi", "Loss Akhir", "Catatan"])
print(df)


/tmp/ipython-input-3969261717.py:10: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-x))
/tmp/ipython-input-3969261717.py:13: RuntimeWarning: overflow encountered in multiply
  return x * (1 - x)
/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:86: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)


  Hidden Size Aktivasi  Loss Akhir                Catatan
0    2 Neuron  Sigmoid         NaN         Lambat belajar
1    3 Neuron  Sigmoid         NaN           Lebih stabil
2    3 Neuron     ReLU    0.125121  Paling cepat & akurat
